name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      working-directory: .
      run: npm install
    - name: Build fresh lib
      working-directory: .
      run: npm run build
    - name: Push lib to master
      run: |
        git config --global user.name 'masachi'
        git config --global user.email 'zhangjb42@gmail.com'
        git add .
        git commit -am "Build fresh lib with Github Actions"
        git push origin v1.1.2
    - name: Sync Lib to Gitee
      run: |
         git remote set-url origin https://masachi:${{ secrets.GITEE_ACCESS_TOKEN }}@gitee.com/masachi/react-ueditor
         git push -f origin v1.1.2
